version: "3.9"  # optional since v1.27.0
services:
  vpn:
    container_name: vpn-container
    image: jackvartanian/dperson-openvpnclient
    build: ./openvpnclient
    volumes:
      - ./openvpnclient/settings:/vpn
    devices:
      - "/dev/net/tun"
    ports:
      - "8000:8000"
    cap_add: 
      - NET_ADMIN

  flask_app:
    container_name: capta-api-container
    depends_on:
       - vpn
    
    network_mode: service:vpn

    #image: jackvartanian/capta-api
    build: ./capta-api
    env_file: 
      - .env

    environment:
    - USER_JV=${USER_JV}
    - PASSWORD_JV=${PASSWORD_JV}
    - SECRET_KEY=${SECRET_KEY}
    - SERVER=${SERVER}
    - DATABASE=${DATABASE}
    - UID=${UID}
    - PWDD=${PWDD}

    volumes: 
      - ./capta-api:/capta-api
    
    command: gunicorn -w 1 --reload -b 0.0.0.0:8000 app.wsgi:app 
    
    
  # reverse-proxy:
  #   container_name: reverse-proxy-container
  #   image: jackvartanian/reverse-proxy
  #   depends_on:
  #     - flask_app
  #   ports:
  #     - "80:80"