version: "3.7"  # optional since v1.27.0
services:
  vpn:
    container_name: vpn-container
    image: dperson/openvpn-client
    devices:
      - "/dev/net/tun"
    ports:
      - "8080:8080"
    volumes:
      - ./vpn/:/vpn
    cap_add: 
      - NET_ADMIN

  api:
    container_name: capta-api-container
    network_mode: service:vpn
    build: capta-api/
    environment:
    - USER_JV=${USER_JV}
    - PASSWORD_JV=${PASSWORD_JV}
    - SECRET_KEY=${SECRET_KEY}
    - SERVER=${SERVER}
    - DATABASE=${DATABASE}
    - UID=${UID}
    - PWDD=${PWDD}
    volumes: 
      - ./capta-api/:/capta-api
    command:  gunicorn -w 3 --reload -b 0.0.0.0:8080 "app.main:start_app(testing=False)"
    
    
