from sqlalchemy import Column, Integer, String, Float, Boolean, LargeBinary
from database.base import Base

class ProductsModel(Base):
    __tablename__ = 'sljpro'

    # String Columns

    cpros = Column(String(10), primary_key=True)
    # caracts = Column(String(500))
    # cclass = Column(String(500))
    # cftiocs = Column(String(500))
    # cftios = Column(String(500))
    # cgrus = Column(String(500))
    # clfiscals = Column(String(500))
    # codacbs = Column(String(500))
    # codccnjs = Column(String(500))
    # codcors = Column(String(500))
    # codcpds = Column(String(500))
    # codfinp = Column(String(500))
    # codident = Column(String(500))
    # codmatp = Column(String(500))
    # codservs = Column(String(500))
    # codtams = Column(String(500))
    # colecoes = Column(String(500))
    # compos = Column(String(500))
    # contaccus = Column(String(500))
    # cproeqs = Column(String(500))
    # cunifors = Column(String(500))
    # cunips = Column(String(500))
    # cunis = Column(String(500))
    # cvens = Column(String(500))
    # descfis = Column(String(500))
    # dpro2s = Column(String(500))
    # dpro3s = Column(String(500))
    # dpros = Column(String(500))
    # gruccus = Column(String(500))
    # idecpros = Column(String(500))
    # linhas = Column(String(500))
    # locals = Column(String(500))
    # matprincs = Column(String(500))
    # mercs = Column(String(500))
    # metals = Column(String(500))
    # mftios = Column(String(500))
    # moecs = Column(String(500))
    # moecusfs = Column(String(500))
    # moedas = Column(String(500))
    # moepcs = Column(String(500))
    # moepvs = Column(String(500))
    # moevs = Column(String(500))
    # multcomps = Column(String(500))
    # nivelqs = Column(String(500))
    # notas = Column(String(500))
    # obsetqs = Column(String(500))
    # obspeds = Column(String(500))
    # obspes = Column(String(500))
    # origmercs = Column(String(500))
    # reffs = Column(String(500))
    # sgrus = Column(String(500))
    # sittricms = Column(String(500))
    # status = Column(String(500))
    # teors = Column(String(500))
    # tipos = Column(String(500))
    # tmontas = Column(String(500))
    # tptribs = Column(String(500))
    # usuincs = Column(String(500))
    # codconc = Column(String(500))
    # codgarras = Column(String(500))
    # descecfs = Column(String(500))
    # cstipis = Column(String(500))
    # cstpiss = Column(String(500))
    # cstcofs = Column(String(500))
    # cinfadpro1 = Column(String(500))
    # cinfadpro2 = Column(String(500))
    # cunipesos = Column(String(500))
    # cmd5_1s = Column(String(500))
    # tabd = Column(String(500))
    # cinfadpro3 = Column(String(500))
    # cinfadpro4 = Column(String(500))
    # dprosits = Column(String(500))
    # dspalchave = Column(String(500))
    # codtpcs = Column(String(500))
    # codscols = Column(String(500))
    # codstils = Column(String(500))
    # cprobals = Column(String(500))
    # moedmeds = Column(String(500))
    # dprosit2s = Column(String(500))
    # nfoto1s = Column(String(500))
    # nfoto2s = Column(String(500))
    # obsetiqs = Column(String(500))
    # dcre = Column(String(500))
    # ccodaux = Column(String(500))
    # multvends = Column(String(500))
    # cest = Column(String(500))
    # ccoddme = Column(String(500))
    # cprocds = Column(String(500))
    # emporigs = Column(String(500))
    # refnfes = Column(String(500))
    # ipis = Column(String(500))
    # moedafob = Column(String(500))
    # ifors = Column(String(500))





    # # Float Columns
    # casas = Column(Float)
    # cbars = Column(Float)
    # cbms = Column(Float)
    # comis = Column(Float)
    # consigs = Column(Float)
    # cravcers = Column(Float)
    # custocvs = Column(Float)
    # custofs = Column(Float)
    # diasinas = Column(Float)
    # digimaxs = Column(Float)
    # encargos = Column(Float)
    # encoms = Column(Float)
    # fabrproprs = Column(Float)
    # fcustos = Column(Float)
    # fvendas = Column(Float)
    # icms = Column(Float)
    # ltmins = Column(Float)
    # ltminsv = Column(Float)
    # margems = Column(Float)
    markcvs = Column(Float)
    # markupa = Column(Float)
    # ordcompos = Column(Float)
    # pcuss = Column(Float)
    # pesobris = Column(Float)
    # pesobs = Column(Float)
    # pesoms = Column(Float)
    # pesomts = Column(Float)
    # pesopdrs = Column(Float)
    # pftiocs = Column(Float)
    # pftios = Column(Float)
    # pidealcvs = Column(Float)
    # pvens = Column(Float)
    # pvideals = Column(Float)
    # qmins = Column(Float)
    # qtdcpnts = Column(Float)
    # qtdias = Column(Float)
    # qtminfabs = Column(Float)
    # retiras = Column(Float)
    # situas = Column(Float)
    # tamhs = Column(Float)
    # tamls = Column(Float)
    # tamps = Column(Float)
    # tents = Column(Float)
    # tinsts = Column(Float)
    # valors = Column(Float)
    # varias = Column(Float)
    # volumes = Column(Float)
    # vultcomps = Column(Float)
    # nidentfixa = Column(Float)
    # pesometal = Column(Float)
    # aliqipis = Column(Float)
    # idpro = Column(Float)
    # extipi = Column(Float)
    # ccodseg = Column(Float)
    # ccoddim = Column(Float)
    # ccodsist = Column(Float)
    # ccodcarac = Column(Float)
    # iats = Column(Float)
    # ajustes = Column(Float)
    # qtdaros = Column(Float)
    # senrepos = Column(Float)
    # implispre = Column(Float)
    # tipoinvs = Column(Float)
    # vultcomp2s = Column(Float)
    # pdifpes = Column(Float)
    # ntpitem = Column(Float)
    # casas1 = Column(Float)
    # idmodal = Column(Float)
    # markupm = Column(Float)
    # unitmeds = Column(Float)
    # qtarosab = Column(Float)
    # qtarosac = Column(Float)
    # gremprs = Column(Float)
    # empilhamx = Column(Float)
    # cxpallet = Column(Float)
    # camadas = Column(Float)
    # vultvend2s = Column(Float)
    # vultvends = Column(Float)
    # envfototr = Column(Float)
    # percperda = Column(Float)
    # varpesos = Column(Float)
    # precofob = Column(Float)
    # transfs = Column(Float)
    # fatetiq = Column(Float)
    # unitmfis = Column(Float)
    # ean13 = Column(Float)
    # montadescs = Column(Float)
    # montagens = Column(Float)
    # idcre = Column(Float)


    # # Integer Columns
    # datas = Column(Integer)
    # datatrans = Column(Integer)
    # dsccompras = Column(Integer)
    # dtcomps = Column(Integer)
    # dtfilms = Column(Integer)
    # dtincs = Column(Integer)
    # figtecs = Column(Integer)
    # obscompras = Column(Integer)
    # ultcomps = Column(Integer)
    dtprecos = Column(Integer)
    # dtpcuss = Column(Integer)
    # imgfigtec = Column(Integer)
    # figsit1s = Column(Integer)
    # figsit2s = Column(Integer)
    # kcdmarca = Column(Integer)
    # proid = Column(Integer)
    # descadpro1 = Column(Integer)
    # descadpro2 = Column(Integer)
    # figsit3s = Column(Integer)
    # dspalchavi = Column(Integer)
    # dproisits = Column(Integer)
    # dproisit2s = Column(Integer)
    # nfoto3s = Column(Integer)
    # ultvends = Column(Integer)


    # # Boolean Columns
    # chkfunds = Column(Boolean)
    flagctabs = Column(Boolean)
    # impetiqs = Column(Boolean)
    # tcomps = Column(Boolean)
    # transps = Column(Boolean)


    # # LargeBinary Columns
    # figjpgs = Column(LargeBinary)

    def __str__(self):
        return f"{self.cpros}"




















   