from sqlalchemy import Column, Integer, String, Float, Boolean, LargeBinary
from sqlalchemy.orm import backref, relationship
from config.database.base import Base

class Products(Base):
    __tablename__ = 'sljpro'

    # String Columns
    caracts = Column(String)
    cclass = Column(String)
    cftiocs = Column(String)
    cftios = Column(String)
    cgrus = Column(String)
    clfiscals = Column(String)
    codacbs = Column(String)
    codccnjs = Column(String)
    codcors = Column(String)
    codcpds = Column(String)
    codfinp = Column(String)
    codident = Column(String)
    codmatp = Column(String)
    codservs = Column(String)
    codtams = Column(String)
    colecoes = Column(String)
    compos = Column(String)
    contaccus = Column(String)
    cproeqs = Column(String)
    cpros = Column(String)
    cunifors = Column(String)
    cunips = Column(String)
    cunis = Column(String)
    cvens = Column(String)
    descfis = Column(String)
    dpro2s = Column(String)
    dpro3s = Column(String)
    dpros = Column(String)
    gruccus = Column(String)
    idecpros = Column(String)
    linhas = Column(String)
    locals = Column(String)
    matprincs = Column(String)
    mercs = Column(String)
    metals = Column(String)
    mftios = Column(String)
    moecs = Column(String)
    moecusfs = Column(String)
    moedas = Column(String)
    moepcs = Column(String)
    moepvs = Column(String)
    moevs = Column(String)
    multcomps = Column(String)
    nivelqs = Column(String)
    notas = Column(String)
    obsetqs = Column(String)
    obspeds = Column(String)
    obspes = Column(String)
    origmercs = Column(String)
    reffs = Column(String)
    sgrus = Column(String)
    sittricms = Column(String)
    status = Column(String)
    teors = Column(String)
    tipos = Column(String)
    tmontas = Column(String)
    tptribs = Column(String)
    usuincs = Column(String)
    codconc = Column(String)
    codgarras = Column(String)
    descecfs = Column(String)
    cstipis = Column(String)
    cstpiss = Column(String)
    cstcofs = Column(String)
    cinfadpro1 = Column(String)
    cinfadpro2 = Column(String)
    cunipesos = Column(String)
    cmd5_1s = Column(String)
    tabd = Column(String)
    cinfadpro3 = Column(String)
    cinfadpro4 = Column(String)
    dprosits = Column(String)
    dspalchave = Column(String)
    codtpcs = Column(String)
    codscols = Column(String)
    codstils = Column(String)
    cprobals = Column(String)
    moedmeds = Column(String)
    dprosit2s = Column(String)
    nfoto1s = Column(String)
    nfoto2s = Column(String)
    obsetiqs = Column(String)
    dcre = Column(String)
    ccodaux = Column(String)
    multvends = Column(String)
    cest = Column(String)
    ccoddme = Column(String)
    cprocds = Column(String)
    emporigs = Column(String)
    refnfes = Column(String)
    ipis = Column(String)
    moedafob = Column(String)





    # Float Columns
    casas = Column(Float)
    cbars = Column(Float)
    cbms = Column(Float)
    comis = Column(Float)
    consigs = Column(Float)
    cravcers = Column(Float)
    custocvs = Column(Float)
    custofs = Column(Float)
    diasinas = Column(Float)
    digimaxs = Column(Float)
    encargos = Column(Float)
    encoms = Column(Float)
    fabrproprs = Column(Float)
    fcustos = Column(Float)
    fvendas = Column(Float)
    icms = Column(Float)
    ltmins = Column(Float)
    ltminsv = Column(Float)
    margems = Column(Float)
    markcvs = Column(Float)
    markupa = Column(Float)
    ordcompos = Column(Float)
    pcuss = Column(Float)
    pesobris = Column(Float)
    pesobs = Column(Float)
    pesoms = Column(Float)
    pesomts = Column(Float)
    pesopdrs = Column(Float)
    pftiocs = Column(Float)
    pftios = Column(Float)
    pidealcvs = Column(Float)
    pvens = Column(Float)
    pvideals = Column(Float)
    qmins = Column(Float)
    qtdcpnts = Column(Float)
    qtdias = Column(Float)
    qtminfabs = Column(Float)
    retiras = Column(Float)
    situas = Column(Float)
    tamhs = Column(Float)
    tamls = Column(Float)
    tamps = Column(Float)
    tents = Column(Float)
    tinsts = Column(Float)
    valors = Column(Float)
    varias = Column(Float)
    volumes = Column(Float)
    vultcomps = Column(Float)
    nidentfixa = Column(Float)
    pesometal = Column(Float)
    aliqipis = Column(Float)
    idpro = Column(Float)
    extipi = Column(Float)
    ccodseg = Column(Float)
    ccoddim = Column(Float)
    ccodsist = Column(Float)
    ccodcarac = Column(Float)
    iats = Column(Float)
    ajustes = Column(Float)
    qtdaros = Column(Float)
    senrepos = Column(Float)
    implispre = Column(Float)
    tipoinvs = Column(Float)
    vultcomp2s = Column(Float)
    pdifpes = Column(Float)
    ntpitem = Column(Float)
    casas1 = Column(Float)
    idmodal = Column(Float)
    markupm = Column(Float)
    unitmeds = Column(Float)
    qtarosab = Column(Float)
    qtarosac = Column(Float)
    gremprs = Column(Float)
    empilhamx = Column(Float)
    cxpallet = Column(Float)
    camadas = Column(Float)
    vultvend2s = Column(Float)
    vultvends = Column(Float)
    envfototr = Column(Float)
    percperda = Column(Float)
    varpesos = Column(Float)
    precofob = Column(Float)
    transfs = Column(Float)
    fatetiq = Column(Float)
    unitmfis = Column(Float)
    ean13 = Column(Float)
    montadescs = Column(Float)
    montagens = Column(Float)
    idcre = Column(Float)


    # Integer Columns
    datas = Column(Integer)
    datatrans = Column(Integer)
    dsccompras = Column(Integer)
    dtcomps = Column(Integer)
    dtfilms = Column(Integer)
    dtincs = Column(Integer)
    figtecs = Column(Integer)
    obscompras = Column(Integer)
    ultcomps = Column(Integer)
    dtprecos = Column(Integer)
    dtpcuss = Column(Integer)
    imgfigtec = Column(Integer)
    figsit1s = Column(Integer)
    figsit2s = Column(Integer)
    kcdmarca = Column(Integer)
    proid = Column(Integer)
    descadpro1 = Column(Integer)
    descadpro2 = Column(Integer)
    figsit3s = Column(Integer)
    dspalchavi = Column(Integer)
    dproisits = Column(Integer)
    dproisit2s = Column(Integer)
    nfoto3s = Column(Integer)
    ultvends = Column(Integer)


    # Boolean Columns
    chkfunds = Column(Boolean)
    flagctabs = Column(Boolean)
    ifors = Column(String)
    impetiqs = Column(Boolean)
    tcomps = Column(Boolean)
    transps = Column(Boolean)


    # LargeBinary Columns
    figjpgs = Column(LargeBinary)






















   